FROM eclipse-temurin:21-alpine


COPY Clab-container/ /opt/app/Clab-container/
WORKDIR /opt/app/Clab-container/
RUN ./mvnw clean install

EXPOSE 8080


CMD ["java", "-jar", "/opt/app/Clab-container/target/container-0.0.1-SNAPSHOT.jar"]

